### ISSUE TITLE
Getting 500 internal error for success calls

### ISSUE THREAD

**Issue by salmangadit** [InfiniteMoments/heisenberg#2]
Hey, so I get this message everytime I make a success call to POST /users, but it stores the item on the database anyway. 

<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  
  <div class="dialog">
    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

Can you please help check? Looks like there is a problem in the response/token generation.

**Comment by salmangadit** [comment]
Same issue on POST /login

**Comment by salmangadit** [comment]
@saiaspire

**Comment by saiaspire** [comment]
@salmangadit please check your json request body

ActionDispatch::ParamsParser::ParseError (795: unexpected token at 'username=postman5565&password=worded'):

Your json body is incorrect format

valid sample:

{
"username" : "username",
"password" : "password"
}

**Comment by salmangadit** [comment]
Your OneNote doesn't mention header json. In fact your postman screenshot shows x-www-form-urlencoded. Hence the issue. Just saw your wiki, making edits on that now.

**Comment by saiaspire** [comment]
Ahh, that was just to show the JWT header
